/** Extra search words per tool (everyday terms people type), used by the header tool search. */
export const TOOL_KEYWORDS: Record<string, string> = {
  "qr-generator": "create make qr code custom logo colour color style design",
  "qr-url": "link website url web address page",
  "qr-wifi": "wifi wi-fi network password guest internet",
  "qr-email": "email e-mail mail mailto",
  "qr-phone": "phone call telephone number mobile",
  "qr-sms": "sms text message",
  "qr-whatsapp": "whatsapp chat message",
  "qr-vcard": "vcard contact business card address book",
  "qr-contact": "contact mecard business card",
  "qr-maps": "google maps location map address directions coordinates",
  "qr-event": "event calendar meeting date",
  "qr-scanner": "scan read camera qr",
  "qr-decoder": "decode read image photo screenshot upload qr",
  "qr-validator": "check test validate verify qr readable",
  "barcode-generator": "create make barcode ean upc code 128 data matrix",
  "barcode-scanner": "scan read camera barcode",
  "barcode-decoder": "decode read image photo screenshot upload barcode",
  "barcode-validator": "check validate verify barcode number",
  "check-digit": "check digit calculate gtin ean upc",
  "ean-upc-validator": "ean upc gtin retail product check validate convert upc-e",
  "itf-14-validator": "itf-14 gtin-14 carton case shipping check validate",
  "bc-ean13": "ean-13 ean13 retail product supermarket gtin",
  "bc-ean8": "ean-8 ean8 small pack retail",
  "bc-upca": "upc-a upc retail product usa america",
  "bc-upce": "upc-e small pack retail",
  "bc-code128": "code 128 shipping label inventory asset",
  "bc-code39": "code 39 industrial part",
  "bc-code93": "code 93 industrial",
  "bc-itf": "itf interleaved 2 of 5 numeric",
  "bc-itf14": "itf-14 carton case shipping outer box gtin-14",
  "bc-codabar": "codabar library blood lab",
  "bc-datamatrix": "data matrix 2d small parts electronics healthcare",
  "bc-pdf417": "pdf417 2d id card boarding pass",
  "bc-aztec": "aztec 2d ticket transport rail",
  scanner: "scan read camera qr barcode universal",
  "bulk-qr": "bulk batch many csv spreadsheet excel zip qr",
  "bulk-barcode": "bulk batch many csv spreadsheet excel zip barcode",
};
