import type { Article } from "../types";

const D = "2026-09-28";

export const BARCODE_ARTICLES: Article[] = [
  {
    slug: "what-is-a-barcode",
    title: "What Is a Barcode and How Does It Work?",
    metaTitle: "What Is a Barcode and How Does It Work?",
    description: "How barcodes store data in bars and spaces, how laser, linear and camera scanners read them, what quiet zones and check digits do, and how formats differ.",
    category: "barcodes", publishedAt: D, updatedAt: D,
    intro: [
      "A barcode is a way of writing a number or short piece of text so that a machine can read it quickly and without mistakes. The classic stripes are a linear or 1D barcode; square codes such as QR codes are 2D barcodes. This guide covers how the stripes carry data and how scanners read them.",
    ],
    body: [
      { type: "h2", id: "history", text: "A short history" },
      { type: "p", text: "The idea was patented in the United States in 1952 by Norman Woodland and Bernard Silver, as a bullseye of rings. It became practical once lasers and computers were cheap enough: the grocery industry adopted the Universal Product Code (UPC) in 1973, and the first retail scan of a UPC was a pack of chewing gum in an Ohio supermarket in June 1974. Europe's EAN system followed a few years later." },
      { type: "h2", id: "bars", text: "How bars and spaces carry data" },
      { type: "p", text: "A linear barcode is read as a sequence of dark bars and light spaces of different widths. The narrowest possible element is one module, and its printed width is called the X-dimension, for example 0.33 mm for a standard-size EAN-13." },
      { type: "p", text: "Each format, or symbology, has its own rules for turning characters into patterns. In EAN-13, each digit is 7 modules wide, made of two bars and two spaces. In Code 39, each character is nine elements, three of them wide. The scanner measures the relative widths and looks the patterns up." },
      { type: "p", text: "Around the data, every linear barcode has:" },
      { type: "ul", items: [
        "Start and stop patterns (or guard bars in EAN/UPC), which tell the scanner where the code begins and ends and which way round it is.",
        "Quiet zones: blank margins at both ends that the scanner uses to find the start. Text or graphics printed into the quiet zone is one of the most common reasons barcodes fail.",
        "Usually a check digit or check character, calculated from the data, so the scanner can detect a misread. See [barcode check digits explained](/blog/barcode-check-digits-explained/).",
        "Often a human-readable line of text underneath, so people can type the number if the scan fails.",
      ] },
      { type: "h2", id: "scanners", text: "How scanners read barcodes" },
      { type: "table", caption: "Types of barcode scanner", head: ["Scanner", "How it works", "Reads"], rows: [
        ["Laser scanner", "Sweeps a red laser line across the code and measures reflected light", "Linear barcodes only"],
        ["Linear imager", "Captures a single line of the image with a light sensor", "Linear barcodes only"],
        ["Area imager (camera)", "Takes a picture and decodes it in software, like a phone", "Linear and 2D codes, in any orientation"],
      ] },
      { type: "p", text: "Laser and linear scanners need to cross all the bars in one sweep, which is why the barcode must be roughly lined up with the beam, and why shorter bars are harder to hit. Camera-based scanners find the code anywhere in the image; phones, and ScanHatch's [barcode scanner](/barcode-scanner/), work this way." },
      { type: "p", text: "Because laser scanners use red light, red bars reflect it like the background and become invisible. Barcodes should use dark bars (black, dark blue or dark green) on a light background." },
      { type: "h2", id: "data", text: "What a barcode number means" },
      { type: "p", text: "A barcode usually contains only an identifier. A product barcode holds a GTIN (Global Trade Item Number), not the product's name or price. The till looks the number up in the shop's database. The same barcode can have a different price in different shops, and scanning a barcode with a phone app only tells you more if the app has its own product database." },
      { type: "h2", id: "formats", text: "Common linear formats" },
      { type: "table", caption: "Widely used linear barcodes", head: ["Format", "Data", "Typical use"], rows: [
        ["[EAN-13](/ean-13-barcode-generator/) and [UPC-A](/upc-a-barcode-generator/)", "13 or 12 digits", "Retail products"],
        ["[EAN-8](/ean-8-barcode-generator/) and [UPC-E](/upc-e-barcode-generator/)", "8 digits", "Small retail packs"],
        ["[Code 128](/code-128-barcode-generator/)", "Any standard text", "Shipping labels, inventory, asset tags"],
        ["[Code 39](/code-39-barcode-generator/)", "Capitals, digits, a few symbols", "Industrial and legacy systems"],
        ["[ITF-14](/itf-14-barcode-generator/)", "14 digits", "Shipping cartons"],
        ["[Codabar](/codabar-barcode-generator/)", "Digits and a few symbols", "Libraries and older systems"],
      ] },
      { type: "h2", id: "2d", text: "2D barcodes" },
      { type: "p", text: "2D barcodes store data both across and down. Stacked codes such as [PDF417](/pdf417-generator/) are rows of linear barcode piled on top of each other. Matrix codes such as QR codes, [Data Matrix](/data-matrix-generator/) and [Aztec](/aztec-generator/) are grids of square modules. They hold far more data, include strong error correction, and need camera-based scanners. [QR code vs barcode](/blog/qr-code-vs-barcode/) compares the two families." },
      { type: "h2", id: "make", text: "Making and checking barcodes" },
      { type: "p", text: "The [Barcode Generator](/barcode-generator/) creates all of these formats as print-ready vector files, calculating check digits where the format has them. To check a number without generating anything, use the [Barcode Validator](/barcode-validator/). Generating a barcode only draws the symbol: numbers for retail products still have to come from GS1." },
    ],
    faq: [
      { q: "Does a barcode contain the price?", a: "No. Product barcodes contain an identifier. The price is looked up in the shop's own system." },
      { q: "Why do some barcodes have numbers under them?", a: "So a person can type the number in if the barcode won't scan." },
      { q: "Can any scanner read any barcode?", a: "No. Laser scanners read only linear barcodes, and scanners are often configured to accept only certain formats." },
    ],
    relatedTools: ["barcode-generator", "barcode-scanner", "barcode-validator", "barcode-decoder"],
    relatedArticles: ["qr-code-vs-barcode", "barcode-check-digits-explained", "ean-13-vs-upc-a"],
    cta: { label: "Create a barcode", href: "/barcode-generator/", text: "15 formats, with check digits calculated and print-ready SVG or PDF." },
  },
  {
    slug: "qr-code-vs-barcode",
    title: "QR Code vs Barcode: Which Should You Use?",
    metaTitle: "QR Code vs Barcode: Differences and Which to Use",
    description: "How QR codes and traditional barcodes differ in capacity, error correction and scanning, and which to use for products, shipping, inventory and marketing.",
    category: "barcodes", publishedAt: D, updatedAt: D,
    intro: [
      "QR codes and traditional barcodes are both barcodes: one draws data in a line of bars, the other in a grid of squares. The right one depends less on the technology than on who or what will scan it, and what they expect.",
    ],
    body: [
      { type: "h2", id: "differences", text: "The key differences" },
      { type: "table", caption: "Linear barcodes compared with QR codes", head: ["", "Linear barcode (e.g. EAN-13, Code 128)", "QR code"], rows: [
        ["Shape", "Bars in one row", "Square grid of modules"],
        ["Typical content", "A number or short code (8–30 characters)", "A link, text, WiFi login or contact, up to thousands of characters"],
        ["Error correction", "Check digit detects errors but can't fix them", "Reed-Solomon, which can rebuild up to about 30% of the data"],
        ["Scanning direction", "Scanner must cross the bars", "Any angle"],
        ["Scanners", "Laser, linear and camera scanners", "Camera-based scanners and phones"],
        ["Space needed", "Long and thin", "Compact square"],
        ["Public familiarity", "Checkout scanners", "Phone cameras open it directly"],
      ] },
      { type: "h2", id: "barcode-wins", text: "When a linear barcode is the right choice" },
      { type: "ul", items: [
        "Retail products: shops' checkout systems expect an EAN-13 or UPC-A carrying a GS1 GTIN. See [EAN-13 vs UPC-A](/blog/ean-13-vs-upc-a/).",
        "Shipping cartons: warehouses scan ITF-14 or GS1-128. See [what ITF-14 is](/blog/what-is-itf-14/).",
        "Existing systems: stock rooms, libraries and asset registers often use laser scanners that can't read QR codes.",
        "Simple IDs on narrow labels, where a thin strip fits better than a square.",
      ] },
      { type: "h2", id: "qr-wins", text: "When a QR code is the right choice" },
      { type: "ul", items: [
        "Anything the public scans with a phone: links, menus, WiFi, contact details, tickets.",
        "More data than a short code: a full address, a URL with parameters, a serial number plus a batch code.",
        "Rough conditions, where error correction helps a damaged code still scan.",
        "Small spaces that are square rather than long.",
      ] },
      { type: "h2", id: "other-2d", text: "Other 2D options" },
      { type: "p", text: "QR isn't the only 2D code. [Data Matrix](/data-matrix-generator/) is common for marking small parts and on healthcare packaging, [PDF417](/pdf417-generator/) on ID cards and printed boarding passes, and [Aztec](/aztec-generator/) on rail tickets. For codes the public scans with their own phones, QR is the safest choice because every phone camera recognises it." },
      { type: "h2", id: "retail-2d", text: "Are QR codes replacing retail barcodes?" },
      { type: "p", text: "Gradually, and alongside rather than instead. GS1, the organisation behind EAN and UPC, is promoting 2D barcodes on product packaging that carry the GTIN plus extra data such as batch and expiry, and has an industry goal (“Sunrise 2027” in the US) for retail checkout systems to be able to scan them. Until checkouts everywhere can, products keep a linear EAN or UPC barcode, and any 2D code is added next to it, not instead." },
      { type: "h2", id: "both", text: "Using both" },
      { type: "p", text: "Many products carry both: the EAN-13 for the checkout, and a QR code linking customers to instructions or recipes. They serve different scanners and don't interfere, as long as each has its own quiet zone. Create them with the [Barcode Generator](/barcode-generator/) and the [QR Code Generator](/qr-code-generator/)." },
    ],
    faq: [
      { q: "Can a phone read ordinary barcodes?", a: "Yes, with a scanning app or a browser-based scanner. Most phones' built-in camera apps recognise QR codes but not linear barcodes." },
      { q: "Can I use a QR code instead of an EAN-13 on my product?", a: "Not for selling in shops today. Retail checkouts expect an EAN-13 or UPC-A. Add a QR code alongside it if you want to link to more information." },
      { q: "Which holds more data?", a: "QR codes, by a wide margin: up to thousands of characters, against a few dozen for linear barcodes." },
    ],
    relatedTools: ["barcode-generator", "qr-generator", "scanner", "barcode-scanner"],
    relatedArticles: ["what-is-a-barcode", "what-is-a-qr-code", "ean-13-vs-upc-a"],
    cta: { label: "Scan either kind", href: "/scanner/", text: "The universal scanner reads QR codes and barcodes from your camera or an image." },
  },
  {
    slug: "barcode-check-digits-explained",
    title: "Barcode Check Digits Explained, With Worked Examples",
    metaTitle: "Barcode Check Digits Explained, With Examples",
    description: "How the GS1 mod 10 check digit for EAN, UPC and ITF-14 is calculated step by step, how Code 39, Code 128 and ISBN-10 differ, and what check digits catch.",
    category: "barcodes", publishedAt: D, updatedAt: D,
    intro: [
      "The last digit of most product barcodes isn't part of the product number. It's a check digit, calculated from all the other digits so that a scanner or a person typing the number can tell when something has gone wrong. This guide shows exactly how the common ones are calculated.",
    ],
    body: [
      { type: "h2", id: "why", text: "Why check digits exist" },
      { type: "p", text: "Scanners occasionally misread a bar, and people often mistype numbers. Without a check, a wrong number could look perfectly valid and be recorded against the wrong product. A check digit is a small calculation over the other digits. If any digit changes, the calculation usually no longer matches, and the error is caught." },
      { type: "h2", id: "gs1", text: "The GS1 mod 10 check digit (EAN, UPC, ITF-14)" },
      { type: "p", text: "EAN-13, EAN-8, UPC-A and ITF-14 (and GTINs in general) share one method:" },
      { type: "ol", items: [
        "Take all the digits except the check digit.",
        "Starting from the rightmost of them and moving left, multiply the digits alternately by 3 and 1.",
        "Add up the results.",
        "The check digit is the amount needed to reach the next multiple of 10 (0 if the total is already a multiple of 10).",
      ] },
      { type: "table", caption: "Worked example: EAN-13 4006381333931", head: ["Digit", "4", "0", "0", "6", "3", "8", "1", "3", "3", "3", "9", "3"], rows: [
        ["Weight", "1", "3", "1", "3", "1", "3", "1", "3", "1", "3", "1", "3"],
        ["Product", "4", "0", "0", "18", "3", "24", "1", "9", "3", "9", "9", "9"],
      ] },
      { type: "p", text: "The products add up to 89. The next multiple of 10 is 90, so the check digit is 90 − 89 = 1, and the complete number is 4006381333931. Because the weights are anchored at the right-hand end, the same rule works for 8, 12, 13 and 14-digit numbers. The [check digit calculator](/check-digit-calculator/) shows this table for any number." },
      { type: "h3", text: "UPC-E: expand first" },
      { type: "p", text: "A UPC-E code is a compressed UPC-A, so its check digit is calculated from the expanded 12-digit form. UPC-E 0425261 expands to UPC-A 04210000526, whose check digit is 4, so the UPC-E is 04252614. The [EAN/UPC validator](/ean-upc-validator/) includes a converter that does the expansion." },
      { type: "h3", text: "ITF-14: a new check digit for each pack" },
      { type: "p", text: "Turning a product's GTIN-13 into a carton's GTIN-14 adds an indicator digit at the front, which changes the calculation. GTIN-13 5012345678900 packed in cases becomes GTIN-14 15012345678907: same 12 middle digits, different check digit. The [ITF-14 validator](/itf-14-validator/) calculates it for you." },
      { type: "h2", id: "catches", text: "What the GS1 check digit catches" },
      { type: "ul", items: [
        "Every error where a single digit is wrong.",
        "Most swaps of two neighbouring digits: 80 of the 90 possible swaps are detected.",
        "It misses swaps of two digits that differ by exactly 5, such as 1 and 6 or 3 and 8, because 3a + b and 3b + a then leave the same remainder.",
        "Some multiple errors cancel out, so it isn't proof that a number is right. It only shows the number is internally consistent.",
      ] },
      { type: "note", text: "A correct check digit doesn't mean a number is registered or belongs to any product. Registration is a separate matter handled by GS1." },
      { type: "h2", id: "other", text: "Other check methods" },
      { type: "h3", text: "Code 39: mod 43 (optional)" },
      { type: "p", text: "Each Code 39 character has a value from 0 to 42 (digits 0–9, then A = 10 up to Z = 35, then - . space $ / + %). Add the values and take the remainder after dividing by 43; the character with that value is the check character. For `CODE39` the values are 12 + 24 + 13 + 14 + 3 + 9 = 75, and 75 mod 43 = 32, which is W, so the barcode would encode CODE39W. Many Code 39 systems don't use a check character at all." },
      { type: "h3", text: "Code 128: mod 103 (always present)" },
      { type: "p", text: "Code 128 always includes a check character, calculated from the start code's value plus each character's value multiplied by its position. For `ABC` in character set B: 104 (start B) + 33×1 + 34×2 + 35×3 = 310, and 310 mod 103 = 1, which is the character “!”. Scanners verify and remove it, so it never appears in the scanned text. [What is Code 128?](/blog/what-is-code-128/) covers the format in detail." },
      { type: "h3", text: "ISBN-10: mod 11" },
      { type: "p", text: "Old 10-digit ISBNs weight the digits 10, 9, 8 … 1 and require the total to be divisible by 11. A remainder that would need 10 is written as X, which is why some ISBNs end in X. Mod 11 catches every single-digit error and every swap of neighbouring digits, but needs that extra symbol. Books now use 13-digit ISBNs with the GS1 method instead." },
      { type: "h3", text: "MSI: mod 10 and mod 11 variants" },
      { type: "p", text: "MSI (Modified Plessey) supports several schemes, including a mod 10 similar to the Luhn check used on payment cards, a mod 11, and doubled versions. The scheme must match what the scanner is set to expect." },
      { type: "h2", id: "tools", text: "Checking a number" },
      { type: "p", text: "The [Barcode Validator](/barcode-validator/) checks the structure and check digit of 12 formats and explains exactly which rule passes or fails. The [Barcode Generator](/barcode-generator/) adds the check digit when you enter a number without it, and tells you when it does." },
    ],
    faq: [
      { q: "Can the check digit be 0?", a: "Yes. When the weighted total is already a multiple of 10, the check digit is 0." },
      { q: "If the check digit is right, is the barcode number valid?", a: "It's internally consistent, but that doesn't mean it's registered or assigned to a product." },
      { q: "Do all barcodes have a check digit?", a: "No. Plain ITF, Codabar and Pharmacode have none, and Code 39's is optional." },
    ],
    relatedTools: ["check-digit", "barcode-validator", "ean-upc-validator", "itf-14-validator"],
    relatedArticles: ["ean-13-vs-upc-a", "what-is-itf-14", "what-is-code-128"],
    cta: { label: "Calculate a check digit", href: "/check-digit-calculator/", text: "EAN-13, EAN-8, UPC-A and ITF-14, with the full calculation shown." },
  },
  {
    slug: "ean-13-vs-upc-a",
    title: "EAN-13 vs UPC-A: What's the Difference?",
    metaTitle: "EAN-13 vs UPC-A: What's the Difference?",
    description: "How EAN-13 and UPC-A relate, why a UPC-A is an EAN-13 starting with 0, where each is used, how to convert them, and which to put on your product.",
    category: "barcodes", publishedAt: D, updatedAt: D,
    intro: [
      "EAN-13 and UPC-A look almost identical and are read by the same scanners. The short answer is that UPC-A is a special case of EAN-13. The details explain why shops in different countries still ask for one or the other.",
    ],
    body: [
      { type: "h2", id: "history", text: "Two systems that merged" },
      { type: "p", text: "The US grocery industry adopted the 12-digit Universal Product Code in 1973. A few years later, European countries created the European Article Numbering system, which added a 13th digit so that each country's numbering organisation could have its own prefixes. EAN was designed to be compatible with UPC: any UPC number can be written as an EAN-13 by putting a 0 in front." },
      { type: "p", text: "The two bodies eventually merged, and since 2005 the combined organisation has been called GS1. Both numbers are now GTINs (Global Trade Item Numbers): a UPC-A carries a GTIN-12, an EAN-13 a GTIN-13." },
      { type: "h2", id: "same", text: "Why a UPC-A is an EAN-13 starting with 0" },
      { type: "p", text: "In an EAN-13 barcode, the first digit isn't drawn as bars. It's encoded in the pattern of how the next six digits are drawn (each can use one of two patterns, called odd and even parity). When the first digit is 0, all six use the odd-parity pattern, which is exactly how UPC-A draws them. So UPC-A 036000291452 and EAN-13 0036000291452 produce the same bars." },
      { type: "example", label: "Example", text: "UPC-A `036000291452` = EAN-13 `0036000291452`. The check digit is the same (2), because adding a leading zero doesn't change the weighted total." },
      { type: "h2", id: "compare", text: "Side by side" },
      { type: "table", caption: "EAN-13 and UPC-A compared", head: ["", "EAN-13", "UPC-A"], rows: [
        ["Digits", "13 (GTIN-13)", "12 (GTIN-12)"],
        ["Bar width", "95 modules", "95 modules"],
        ["Human-readable text", "First digit to the left, then two groups of six", "First and last digits smaller, outside the bars"],
        ["Issued mainly in", "Most of the world", "United States and Canada"],
        ["Read at checkouts", "Worldwide", "Worldwide"],
        ["Check digit", "GS1 mod 10", "GS1 mod 10"],
      ] },
      { type: "h2", id: "scanners", text: "Will my barcode scan in other countries?" },
      { type: "p", text: "Yes, in both directions. Retail scanners worldwide read both formats. The last big gap closed in 2005, when US and Canadian retailers were asked to make their systems accept 13-digit EAN codes (the “Sunrise 2005” deadline). A product with an EAN-13 can be sold in North America, and a UPC-A product in Europe." },
      { type: "p", text: "Scanners and databases often report a UPC-A in its 13-digit form with a leading zero, or even as a 14-digit GTIN padded with zeros. It's the same number." },
      { type: "h2", id: "convert", text: "Converting between them" },
      { type: "ul", items: [
        "UPC-A to EAN-13: always possible, by adding a leading 0. The check digit stays the same.",
        "EAN-13 to UPC-A: possible only when the EAN-13 starts with 0. An EAN-13 starting with any other digit has no UPC-A form.",
        "UPC-A to UPC-E: possible only for numbers with zeros in particular positions. See the [UPC-E generator](/upc-e-barcode-generator/).",
      ] },
      { type: "h2", id: "choose", text: "Which should you use?" },
      { type: "p", text: "Use the number GS1 gives you. If you license numbers from GS1 US, you'll receive a company prefix that produces 12-digit GTINs, and you'd normally print them as UPC-A. Most other GS1 member organisations issue 13-digit GTINs for EAN-13. Either will scan at checkouts in the other region." },
      { type: "note", text: "A barcode generator draws the barcode for a number you already have. It doesn't register the number. Retailers and marketplaces generally expect GTINs licensed from GS1 or an authorised reseller." },
      { type: "h2", id: "make", text: "Creating and checking them" },
      { type: "p", text: "Generate either with the [EAN-13 barcode generator](/ean-13-barcode-generator/) or the [UPC-A barcode generator](/upc-a-barcode-generator/). Both calculate the check digit if you enter the number without it. To check an existing number, including its check digit and what its prefix means, use the [EAN/UPC validator](/ean-upc-validator/)." },
    ],
    faq: [
      { q: "Can I use an EAN-13 barcode in the US?", a: "Yes. US retail systems have accepted 13-digit EAN codes since 2005." },
      { q: "Why does my UPC show 13 digits in a scanning app?", a: "Many apps show the 13-digit GTIN form, which is the UPC-A with a 0 in front. It's the same number." },
      { q: "Is EAN-13 the same as a GTIN?", a: "EAN-13 is the barcode; the 13-digit number it carries is a GTIN-13." },
    ],
    relatedTools: ["bc-ean13", "bc-upca", "ean-upc-validator", "check-digit"],
    relatedArticles: ["barcode-check-digits-explained", "what-is-a-barcode", "qr-code-vs-barcode"],
    cta: { label: "Validate an EAN or UPC number", href: "/ean-upc-validator/", text: "Check the digits, see what the prefix means, and convert UPC-E." },
  },
  {
    slug: "what-is-code-128",
    title: "What Is Code 128? Character Sets, Check Characters and GS1-128",
    metaTitle: "What Is Code 128? Character Sets, Checks and GS1-128",
    description: "How Code 128 works: character sets A, B and C, why numbers compress to half the width, the mod 103 check character, and GS1-128 Application Identifiers.",
    category: "barcodes", publishedAt: D, updatedAt: D,
    intro: [
      "Code 128 is the workhorse of shipping labels, warehouse systems and asset tags. It can encode any standard keyboard character, and it's one of the most compact linear barcodes available. Here's how it manages both, and how its GS1-128 variant carries structured supply-chain data.",
    ],
    body: [
      { type: "h2", id: "structure", text: "The structure of a Code 128 barcode" },
      { type: "p", text: "Code 128 was introduced in 1981 and is standardised as ISO/IEC 15417. Every symbol character is 11 modules wide, made of three bars and three spaces, each 1 to 4 modules wide. The name comes from its ability to encode all 128 ASCII characters. A barcode is:" },
      { type: "ol", items: [
        "A quiet zone of at least 10 modules.",
        "A start character, which also selects the first character set (A, B or C).",
        "The data characters.",
        "A check character.",
        "A stop pattern (13 modules), and another quiet zone.",
      ] },
      { type: "h2", id: "sets", text: "Character sets A, B and C" },
      { type: "table", caption: "Code 128 character sets", head: ["Set", "Contains", "Useful for"], rows: [
        ["A", "Capital letters, digits, punctuation and control characters (such as tab)", "Uppercase data with control codes"],
        ["B", "Capital and lowercase letters, digits and punctuation", "Ordinary text"],
        ["C", "The 100 digit pairs 00 to 99", "Numbers: two digits per character"],
      ] },
      { type: "p", text: "Special shift and code-change characters let a barcode switch sets partway through, so a value like `ABC123456` can be letters in set B followed by digit pairs in set C. Good encoders, including the one ScanHatch uses, choose the switches that give the shortest result, so you never need to pick a set yourself." },
      { type: "h2", id: "compression", text: "Why numbers make shorter barcodes" },
      { type: "p", text: "Set C packs two digits into each 11-module character. That makes numeric data about half as wide as text of the same length:" },
      { type: "table", caption: "Width of Code 128 barcodes (without quiet zones), measured with the ScanHatch encoder", head: ["Data", "Characters used", "Width"], rows: [
        ["`ABCDEF`", "Start B, 6 letters, check, stop", "101 modules"],
        ["`123456`", "Start C, 3 digit pairs, check, stop", "68 modules"],
        ["`12345678901234`", "Start C, 7 digit pairs, check, stop", "112 modules"],
      ] },
      { type: "p", text: "Fourteen digits take barely more room than six letters. This is why Code 128 is preferred over Code 39 for long numeric IDs." },
      { type: "h2", id: "check", text: "The mod 103 check character" },
      { type: "p", text: "Every Code 128 barcode has a check character. Its value is the start character's value plus each data character's value multiplied by its position, divided by 103; the remainder is the check value. For `ABC` in set B: 104 + 33×1 + 34×2 + 35×3 = 310, and 310 mod 103 = 1. Scanners verify it and then drop it, so you never see it in the scanned text. [Barcode check digits explained](/blog/barcode-check-digits-explained/) compares it with other methods." },
      { type: "h2", id: "gs1-128", text: "GS1-128: Code 128 with a data structure" },
      { type: "p", text: "GS1-128 is Code 128 with a special function character (FNC1) straight after the start, followed by data in Application Identifier (AI) format. Each AI is a number in brackets that says what the following data means. Common ones:" },
      { type: "table", caption: "Some common GS1 Application Identifiers", head: ["AI", "Meaning", "Format"], rows: [
        ["(00)", "SSCC: serial number for a pallet or shipment", "18 digits"],
        ["(01)", "GTIN of the trade item", "14 digits"],
        ["(10)", "Batch or lot number", "Up to 20 characters"],
        ["(17)", "Expiry date", "YYMMDD"],
      ] },
      { type: "example", label: "Example (fictional data)", text: "`(01)15012345678907(17)271231(10)LOT42` means GTIN 15012345678907, expiring 31 December 2027, batch LOT42. The brackets are printed in the human-readable text but aren't encoded in the bars." },
      { type: "p", text: "ScanHatch generates standard Code 128, not GS1-128. A GS1-128 label needs the FNC1 character and correct AI formatting, and retailers' logistics systems reject labels that get them wrong." },
      { type: "h2", id: "choose", text: "When to choose Code 128" },
      { type: "ul", items: [
        "Internal IDs: stock locations, asset tags, document and sample tracking.",
        "Mixed letters and numbers, including lowercase, which Code 39 can't encode.",
        "Long numeric IDs, where set C keeps the barcode short.",
        "Not for retail products (use EAN-13 or UPC-A) and not for non-English characters, which scanners don't handle reliably.",
      ] },
      { type: "h2", id: "printing", text: "Printing tips" },
      { type: "ul", items: [
        "Keep 10 modules of blank space at each end.",
        "Bars should be at least 15% as tall as the barcode is long, and not less than about 6 mm, so handheld scanners can hit them.",
        "Beyond about 20 to 30 characters the barcode gets long; consider a 2D code such as Data Matrix instead.",
      ] },
      { type: "p", text: "Create one with the [Code 128 generator](/code-128-barcode-generator/), or many at once from a spreadsheet with the [Bulk Barcode Generator](/bulk-barcode-generator/)." },
    ],
    faq: [
      { q: "Is Code 128 better than Code 39?", a: "For most new uses, yes. It's more compact, supports lowercase, and always has a check character. Code 39 remains where existing systems require it." },
      { q: "Do I need to choose set A, B or C?", a: "No. The encoder selects and switches sets automatically for the shortest barcode." },
      { q: "Is GS1-128 the same as Code 128?", a: "GS1-128 is Code 128 with an FNC1 character and GS1 Application Identifiers. Every GS1-128 is a Code 128, but not the other way round." },
    ],
    relatedTools: ["bc-code128", "barcode-generator", "barcode-validator", "bulk-barcode"],
    relatedArticles: ["barcode-check-digits-explained", "what-is-itf-14", "what-is-a-barcode"],
    cta: { label: "Create a Code 128 barcode", href: "/code-128-barcode-generator/", text: "Type any standard text; the shortest encoding is chosen for you." },
  },
  {
    slug: "what-is-itf-14",
    title: "What Is ITF-14? GTIN-14 Barcodes for Cartons Explained",
    metaTitle: "What Is ITF-14? GTIN-14 Carton Barcodes Explained",
    description: "What ITF-14 barcodes are, how a GTIN-14 is built with an indicator digit, where ITF-14 fits in the packaging hierarchy, and how to print it on cartons.",
    category: "barcodes", publishedAt: D, updatedAt: D,
    intro: [
      "ITF-14 is the barcode printed on the outside of shipping cartons, usually inside a thick black frame. It identifies a case of products rather than the product itself. Getting its number right matters more than its appearance, so this guide starts there.",
    ],
    body: [
      { type: "h2", id: "hierarchy", text: "Where ITF-14 fits: the packaging hierarchy" },
      { type: "table", caption: "Identifiers at each packaging level", head: ["Level", "Example", "Identifier", "Usual barcode"], rows: [
        ["Consumer unit", "One bottle sold at the till", "GTIN-13 or GTIN-12", "EAN-13 or UPC-A"],
        ["Inner pack", "A shrink-wrapped 6-pack", "GTIN-14 (or GTIN-13)", "ITF-14 or EAN-13"],
        ["Case", "A carton of 24 bottles", "GTIN-14", "ITF-14"],
        ["Pallet or shipment", "A pallet of mixed cartons", "SSCC (serial shipping container code)", "GS1-128"],
      ] },
      { type: "p", text: "Each different pack configuration needs its own identifier, so a warehouse knows whether it's receiving a case of 6 or a case of 24. Pallets are different: they're identified by a serial number (SSCC) rather than a product number, and use a GS1-128 label (see [what is Code 128](/blog/what-is-code-128/))." },
      { type: "h2", id: "gtin14", text: "Building a GTIN-14" },
      { type: "p", text: "A GTIN-14 has three parts:" },
      { type: "ol", items: [
        "An indicator digit, 1 to 8, assigned by you to tell pack configurations of the same product apart. 9 is reserved for variable-measure items, and 0 means the case uses the inner item's own GTIN.",
        "The first 12 digits of the product's GTIN-13 (for a UPC-A, its 11 digits with a leading 0).",
        "A new check digit, calculated over all 13 preceding digits.",
      ] },
      { type: "example", label: "Worked example (fictional numbers)", text: "Product GTIN-13: `5012345678900`. Remove its check digit to get `501234567890`, add indicator 1 in front to get `1501234567890`, then calculate the GTIN check digit: the weighted sum is 93, so the check digit is 7. The case's GTIN-14 is `15012345678907`." },
      { type: "p", text: "The check digit changes because the indicator digit is part of the calculation, so you can't simply put a 1 in front of a product's EAN-13. The [ITF-14 validator](/itf-14-validator/) does this calculation, and [barcode check digits explained](/blog/barcode-check-digits-explained/) shows the method." },
      { type: "h2", id: "symbology", text: "Why cartons use Interleaved 2 of 5" },
      { type: "p", text: "The ITF-14 barcode uses the Interleaved 2 of 5 symbology, in which digits are encoded in pairs: one digit in five bars, the next in the five spaces between them, two of each five being wide. It's compact for numbers and tolerant of the uneven printing typical of corrugated cardboard, where flexible printing plates press ink onto a ridged surface." },
      { type: "h3", text: "Bearer bars" },
      { type: "p", text: "The thick frame around an ITF-14 is a bearer bar. It spreads the pressure of the printing plate evenly, and stops a scanner reading a partial code when its beam clips the top or bottom of the bars. Without it, a short scan of Interleaved 2 of 5 can occasionally produce a valid-looking but wrong number." },
      { type: "h2", id: "printing", text: "Printing ITF-14 on cartons" },
      { type: "ul", items: [
        "Print it large: GS1 specifications allow narrow bars from roughly 0.5 mm to 1 mm wide, with bars around 32 mm tall.",
        "Keep the full bearer bar and at least 10 narrow-bar widths of blank space inside it at each end.",
        "Place the barcode on at least two adjacent sides of the case, so it can be scanned whichever way the case faces on a conveyor or shelf.",
        "Test a printed carton with the scanner used at goods-in, not just the digital file.",
      ] },
      { type: "h2", id: "mistakes", text: "Common mistakes" },
      { type: "ul", items: [
        "Printing the product's EAN-13 on the outer case, so the warehouse books in one unit instead of a case of 24.",
        "Using the same GTIN-14 for two different pack sizes.",
        "Putting an indicator digit in front of an EAN-13 without recalculating the check digit.",
        "Shrinking the barcode to fit the artwork. ITF-14 is meant to be large.",
      ] },
      { type: "h2", id: "vs-retail", text: "ITF-14 or EAN-13 on the outer case?" },
      { type: "p", text: "If the case itself is sold to shoppers at a checkout, as with a multipack of drinks, it's a consumer unit and carries an EAN-13 or UPC-A. If it only moves through warehouses and distribution, it carries an ITF-14. Some cases carry both. [QR code vs barcode](/blog/qr-code-vs-barcode/) covers where 2D codes fit in." },
    ],
    faq: [
      { q: "Can I use my product's EAN-13 on the carton?", a: "Only if the carton is itself sold as a retail unit. Cases usually need their own GTIN-14 with an indicator digit." },
      { q: "Who assigns the indicator digit?", a: "You do, as the brand owner, within your GS1 company prefix. Use a different indicator for each pack configuration." },
      { q: "Is ITF-14 the same as Interleaved 2 of 5?", a: "ITF-14 uses Interleaved 2 of 5 with exactly 14 digits, a GS1 check digit and bearer bars." },
    ],
    relatedTools: ["bc-itf14", "itf-14-validator", "check-digit", "barcode-scanner"],
    relatedArticles: ["barcode-check-digits-explained", "what-is-code-128", "qr-code-vs-barcode"],
    cta: { label: "Create an ITF-14 barcode", href: "/itf-14-barcode-generator/", text: "Enter 13 digits and the check digit is added, with the bearer frame included." },
  },
];
