import type { Article } from "../types";

const D = "2026-09-28";

export const QR_BASICS: Article[] = [
  {
    slug: "what-is-a-qr-code",
    title: "What Is a QR Code? How QR Codes Work",
    metaTitle: "What Is a QR Code? How QR Codes Work",
    description: "What a QR code is, where it came from, and how a phone turns the black-and-white squares back into a link or text: finder patterns, versions, modes, masking and error correction.",
    category: "qr-codes", publishedAt: D, updatedAt: D,
    intro: [
      "A QR code is a square, two-dimensional barcode that stores text: often a web address, but also WiFi details, contact cards or plain messages. Any phone camera can read one in a fraction of a second, and it still works when part of it is dirty or covered.",
      "This guide explains what the parts of a QR code do and what actually happens between pointing your camera and seeing a link, without assuming any technical background.",
    ],
    body: [
      { type: "h2", id: "origin", text: "Where QR codes came from" },
      { type: "p", text: "QR stands for Quick Response. The code was developed in 1994 by Denso Wave, then part of the Japanese car-parts maker Denso, to track components on production lines faster than traditional barcodes allowed. A linear barcode holds a couple of dozen characters and must be scanned along one line; a QR code stores data in both directions, so it can hold far more and be read from any angle." },
      { type: "p", text: "Denso Wave chose not to enforce its patent, and the format is published as the international standard ISO/IEC 18004. That openness is a large part of why QR codes spread from factories to menus, tickets and payment terminals. “QR Code” itself remains a registered trademark of Denso Wave." },
      { type: "h2", id: "anatomy", text: "The parts of a QR code" },
      { type: "p", text: "Every square in a QR code is called a module. Some modules carry your data, but many have fixed jobs that help the scanner find and read the code:" },
      { type: "table", caption: "Structural parts of a QR code", head: ["Part", "What it looks like", "What it does"], rows: [
        ["Finder patterns", "Three large squares-within-squares in the corners", "Let the scanner find the code and work out its angle and orientation"],
        ["Separators", "A one-module white border around each finder pattern", "Keep the finder patterns distinct from the data"],
        ["Timing patterns", "Alternating dark and light lines between the finder patterns", "Tell the scanner how big each module is, so it can map the grid"],
        ["Alignment patterns", "Smaller squares (from version 2 upwards)", "Help correct distortion when the code is curved or photographed at an angle"],
        ["Format information", "Strips next to the finder patterns", "Record the error-correction level and the mask pattern used"],
        ["Version information", "Two small blocks (version 7 and above)", "Record the code's size, for larger codes"],
        ["Quiet zone", "The blank margin around the code", "Separates the code from its surroundings; the standard asks for 4 modules"],
      ] },
      { type: "p", text: "Everything else is data and error-correction information, laid out in a zigzag path that fills the remaining space." },
      { type: "h2", id: "versions", text: "Versions: why QR codes come in different sizes" },
      { type: "p", text: "QR codes come in 40 sizes called versions. Version 1 is a grid of 21 × 21 modules, and each version adds four modules per side, up to version 40 at 177 × 177. The generator picks the smallest version that fits your data." },
      { type: "example", label: "Example", text: "The address `https://example.com/menu` fits in a version 2 code (25 × 25 modules). A 113-character link with tracking parameters needs version 6 (41 × 41), or version 10 (57 × 57) at the highest error-correction level. More data means more, smaller modules for the same printed size." },
      { type: "p", text: "That's why short links scan more easily: at the same printed width, a code with fewer modules has bigger modules, which phone cameras resolve more reliably." },
      { type: "h2", id: "modes", text: "How the data is encoded" },
      { type: "p", text: "Before anything is drawn, the text is converted into bits using one or more encoding modes. Each mode is efficient for a particular kind of character:" },
      { type: "table", caption: "QR encoding modes", head: ["Mode", "Characters", "Maximum in a version 40 code (lowest error correction)"], rows: [
        ["Numeric", "Digits 0–9", "7,089 digits"],
        ["Alphanumeric", "0–9, capital A–Z, space and $ % * + - . / :", "4,296 characters"],
        ["Byte", "Any bytes, usually UTF-8 text including lowercase and emoji", "2,953 bytes"],
        ["Kanji", "Japanese Kanji characters", "1,817 characters"],
      ] },
      { type: "p", text: "Those maximums are rarely useful in practice: a code holding thousands of characters is dense and hard to scan. Most real QR codes hold under 100 characters." },
      { type: "h2", id: "error-correction", text: "Error correction: why damaged codes still scan" },
      { type: "p", text: "QR codes include extra Reed-Solomon error-correction data, which lets the scanner rebuild missing or misread parts. There are four levels: L, M, Q and H, which restore roughly 7%, 15%, 25% and 30% of the data. Higher levels make the code bigger for the same content. This is also how a logo can sit in the middle of a code: it covers modules, and error correction fills in the gap. [QR code error correction explained](/blog/qr-code-error-correction-explained/) goes into the details." },
      { type: "h2", id: "masking", text: "Masking: why every code looks random" },
      { type: "p", text: "If data were drawn directly, some codes would contain large solid blocks or patterns that look like finder patterns, confusing scanners. So the encoder applies one of eight mask patterns, flipping modules in a regular pattern, and picks the mask that produces the most even-looking result. The format information records which mask was used so the scanner can undo it." },
      { type: "h2", id: "scanning", text: "What happens when you scan a code" },
      { type: "ol", items: [
        "The camera looks for the three finder patterns, which are distinctive at any angle and size.",
        "From their positions it works out the code's orientation, and uses the timing and alignment patterns to map every module, even if the code is tilted or on a curved surface.",
        "It reads the format information to learn the error-correction level and mask.",
        "It removes the mask, reads the data and error-correction codewords, and repairs any errors.",
        "It decodes the bits back into text, then decides what to offer you: open a link, join WiFi, add a contact, or just show the text.",
      ] },
      { type: "p", text: "The code itself doesn't do anything. It's just stored text. Your phone decides how to act on it, which is why a phone asks before opening a link or joining a network. You can see exactly what a code contains, without acting on it, with the [QR code scanner](/qr-scanner/) or the [QR decoder](/qr-decoder/) for images." },
      { type: "h2", id: "variants", text: "Other kinds of QR code" },
      { type: "ul", items: [
        "Micro QR: a smaller variant with one finder pattern, for tiny items. It holds up to 35 digits.",
        "rMQR (rectangular Micro QR): a rectangular version for narrow spaces such as the edge of a label.",
        "Frame QR, iQR and SQRC are further Denso Wave variants for special uses; they're uncommon outside Japan.",
      ] },
      { type: "p", text: "The codes people meet day to day, and the ones the [ScanHatch QR Code Generator](/qr-code-generator/) makes, are standard QR codes (formally QR Code Model 2)." },
      { type: "h2", id: "limits", text: "What QR codes can't do" },
      { type: "ul", items: [
        "They can't hold files, photos or videos. Those are too big; codes link to them instead.",
        "They don't expire by themselves, and they can't be edited once printed. What changes is where a link points, which is the idea behind [static and dynamic QR codes](/blog/static-vs-dynamic-qr-codes/).",
        "They can't prove a link is safe. A QR code is only as trustworthy as whoever put it there.",
      ] },
    ],
    faq: [
      { q: "Do QR codes need the internet?", a: "No. The code's content is stored in the pattern, so a phone can read it offline. Opening a link it contains needs a connection, but reading WiFi details or a contact card doesn't." },
      { q: "Can a QR code be read upside down?", a: "Yes. The three finder patterns tell the scanner the code's orientation, so it can be read at any angle." },
      { q: "Is there a limit to how many QR codes can exist?", a: "No. A QR code is just a way of drawing text, so there's no central register and nothing to run out of." },
    ],
    relatedTools: ["qr-generator", "qr-scanner", "qr-decoder", "qr-validator"],
    relatedArticles: ["what-can-a-qr-code-contain", "qr-code-error-correction-explained", "how-to-scan-a-qr-code"],
    cta: { label: "Create a QR code", href: "/qr-code-generator/", text: "Try it: make a QR code for a link, WiFi network or contact, and download it in print quality." },
  },
  {
    slug: "what-can-a-qr-code-contain",
    title: "What Information Can a QR Code Contain?",
    metaTitle: "What Information Can a QR Code Contain?",
    description: "The kinds of content a QR code can hold, from links and WiFi logins to contact cards, messages, locations and events, with the exact formats phones recognise and the limits on size.",
    category: "qr-codes", publishedAt: D, updatedAt: D,
    intro: [
      "Every QR code contains text, nothing more. What makes one code open a website and another join a WiFi network is the format of that text. Phones recognise a handful of standard formats and offer a matching action.",
      "Below are the formats that work on today's phones, what each looks like inside the code, and what doesn't fit in a QR code at all.",
    ],
    body: [
      { type: "h2", id: "text-only", text: "It's always text" },
      { type: "p", text: "A QR code stores a sequence of characters. When a phone scans it, the camera app looks at the start of that text. If it begins with `https://`, it's a link; if it begins with `WIFI:`, it's a network; if it begins with `BEGIN:VCARD`, it's a contact. Anything it doesn't recognise is shown as plain text." },
      { type: "p", text: "That also means you can see exactly what a code does before acting on it, by reading the raw text with a [QR decoder](/qr-decoder/)." },
      { type: "h2", id: "formats", text: "Formats phones recognise" },
      { type: "table", caption: "Common QR code content formats (all example data is fictional)", head: ["Content", "What the text looks like", "What the phone offers"], rows: [
        ["Web link", "`https://example.com/menu`", "Open the page in the browser"],
        ["WiFi network", "`WIFI:T:WPA;S:Example Guest;P:correct-horse-42;;`", "Join the network"],
        ["Contact (vCard)", "`BEGIN:VCARD` … `END:VCARD` with name, phone, email", "Add to contacts"],
        ["Contact (MeCard)", "`MECARD:N:Doe,Alex;TEL:+447700900123;;`", "Add to contacts"],
        ["Email", "`mailto:hello@example.com?subject=Order%2042`", "Start an email draft"],
        ["Phone call", "`tel:+442079460123`", "Open the dialler"],
        ["Text message", "`SMSTO:+447700900123:JOIN`", "Start a text message"],
        ["Location", "`geo:51.5055,-0.0754` or a Google Maps link", "Open a map (support for geo: varies)"],
        ["Calendar event", "`BEGIN:VEVENT` … `END:VEVENT` with title and times", "Add to calendar (support varies)"],
        ["Plain text", "Any other text", "Show the text"],
      ] },
      { type: "p", text: "The [QR Code Generator](/qr-code-generator/) builds each of these for you, including the escaping rules that trip people up, such as a semicolon inside a WiFi password. Guides for the most common types: [WiFi](/wifi-qr-code-generator/), [website links](/url-qr-code-generator/), [contact cards](/vcard-qr-code-generator/), [email](/email-qr-code-generator/), [phone](/phone-qr-code-generator/), [SMS](/sms-qr-code-generator/), [WhatsApp](/whatsapp-qr-code-generator/) and [Google Maps](/google-maps-qr-code-generator/)." },
      { type: "h3", text: "Links that open apps" },
      { type: "p", text: "Many “app” QR codes are ordinary web links that an app has registered to handle. A WhatsApp code contains `https://wa.me/447700900123`, which opens WhatsApp if it's installed and WhatsApp's website if not. Google Maps, app store and social-profile codes work the same way. Because they're normal links, they degrade gracefully on phones without the app." },
      { type: "h3", text: "Formats with patchy support" },
      { type: "p", text: "Calendar events and `geo:` locations are standard formats, but not every camera app acts on them: some just show the text. For locations, a Google Maps link is the more dependable choice. For events, test on both iPhone and Android before printing." },
      { type: "h2", id: "how-much", text: "How much can a QR code hold?" },
      { type: "p", text: "The absolute maximum is 2,953 bytes of text (or 7,089 digits) in the largest version at the lowest error correction. In practice the limit is how dense a code you're willing to print and scan. A few rules of thumb:" },
      { type: "ul", items: [
        "Under about 100 characters: small, open codes that scan instantly. Most links, WiFi codes and phone numbers are here.",
        "A few hundred characters, such as a full vCard with an address: the code gets noticeably denser and needs printing larger.",
        "Over 1,000 characters: technically possible, but hard to scan with a phone. Put the content on a web page and link to it.",
      ] },
      { type: "p", text: "Non-English text uses more space: accented letters take two bytes in UTF-8, and many Asian scripts and emoji take three or four." },
      { type: "h2", id: "cannot", text: "What a QR code can't contain" },
      { type: "ul", items: [
        "Files, PDFs, images, audio or video. Upload them somewhere and encode the link.",
        "Anything that changes after printing, such as a price or an opening time. The code shows what was encoded on the day it was made.",
        "Hidden or executable content. A code can't install software or run anything on its own; at most it contains a link that the phone asks you about.",
        "Secrets. Anything in a code, WiFi passwords included, can be read by anyone who scans it.",
      ] },
      { type: "h2", id: "checking", text: "Checking a code's content" },
      { type: "p", text: "Before printing a batch, it's worth confirming the content is well-formed: a WiFi code with a missing network name, or a link with a space in it, will scan but won't work. The [QR Validator](/qr-validator/) decodes an image and checks the content against the rules for its type." },
    ],
    faq: [
      { q: "Can a QR code contain a PDF?", a: "Not the file itself. Upload the PDF to a website or cloud storage and make a QR code for its link." },
      { q: "Can a QR code contain a virus?", a: "A QR code only contains text. The risk is a link that leads to a harmful website, so check where a link goes before opening it." },
      { q: "Can I put two things in one QR code, like a link and a WiFi login?", a: "No. Phones act on one format per code. Use two codes, or link to a page that holds both." },
    ],
    relatedTools: ["qr-generator", "qr-decoder", "qr-validator", "qr-scanner"],
    relatedArticles: ["what-is-a-qr-code", "how-to-create-a-qr-code", "how-to-create-a-wifi-qr-code"],
    cta: { label: "Open the QR Code Generator", href: "/qr-code-generator/", text: "Pick a content type and the generator formats the text correctly for you." },
  },
  {
    slug: "how-to-scan-a-qr-code",
    title: "How to Scan a QR Code on iPhone, Android or a Computer",
    metaTitle: "How to Scan a QR Code on iPhone, Android or Computer",
    description: "How to scan a QR code with an iPhone, an Android phone or a computer, how to read a code from a screenshot, what to do when a code won't scan, and how to check a link is safe.",
    category: "scanning", publishedAt: D, updatedAt: D,
    intro: [
      "Most phones can scan QR codes with the built-in camera, no app needed. This guide covers the quickest way on each kind of device, how to read a code that's already on your screen, and what to try when a code refuses to scan.",
    ],
    body: [
      { type: "h2", id: "iphone", text: "On an iPhone or iPad" },
      { type: "ol", items: [
        "Open the Camera app and point it at the code. You don't need to take a photo.",
        "When the code is recognised, a yellow link or notification appears. Tap it to open the link or action.",
      ] },
      { type: "p", text: "iPhones have read QR codes in the Camera app since iOS 11. There's also a dedicated Code Scanner you can add to Control Centre, which is handy in low light because it has its own torch button." },
      { type: "h2", id: "android", text: "On an Android phone" },
      { type: "p", text: "Most recent Android phones read QR codes in the standard camera app: point, wait for the pop-up, tap it. Some manufacturers put the feature behind a lens or scan mode, or in the camera settings. If your camera doesn't react, Google Lens (in the Google app, or often in the camera itself) reads QR codes on almost every Android phone." },
      { type: "p", text: "Android also has a scanner in the WiFi settings: open the network list and look for a QR icon next to “Add network”. It's useful for WiFi codes when the camera app only shows the raw text." },
      { type: "h2", id: "computer", text: "On a laptop or desktop computer" },
      { type: "p", text: "Computers don't usually scan QR codes out of the box. Two options work in any modern browser:" },
      { type: "ul", items: [
        "Use a webcam: the [ScanHatch scanner](/qr-scanner/) reads codes held up to your laptop camera, entirely in the browser.",
        "Use an image: if the code is in an email or document, take a screenshot and upload or paste it into the [QR decoder](/qr-decoder/).",
      ] },
      { type: "h2", id: "screenshot", text: "Scanning a code that's on your own screen" },
      { type: "p", text: "It's awkward to scan a code shown on the same phone you'd scan it with, for example in a message or a PDF ticket. Take a screenshot instead, then:" },
      { type: "ul", items: [
        "On iPhone, open the screenshot in Photos. Recent versions of iOS detect the code and show a QR button or link.",
        "On Android, open the screenshot with Google Lens.",
        "On any device, upload it to the [QR decoder](/qr-decoder/), which also shows exactly what the code contains.",
      ] },
      { type: "h2", id: "troubleshooting", text: "When a QR code won't scan" },
      { type: "table", caption: "Common scanning problems and fixes", head: ["Problem", "What to try"], rows: [
        ["Nothing happens", "Move back a little. Phones can't focus closer than roughly 10 cm, and the whole code (with some margin) needs to be in view."],
        ["Code is small or far away", "Zoom in slightly rather than moving closer, or move closer until the code fills about half the screen."],
        ["Glare or reflections", "Tilt the phone or the code so light doesn't bounce off glossy paper, laminate or a screen."],
        ["Dark room", "Turn on the torch, or increase the brightness of the screen showing the code."],
        ["Code on a curved or crumpled surface", "Flatten it, or scan from straight on so less of it is distorted."],
        ["Light code on a dark background", "Some scanners can't read inverted codes. Try Google Lens, or a scanner app that supports them."],
        ["Only shows text, no button", "The phone doesn't recognise the format, for example some calendar codes. You can still copy the text."],
      ] },
      { type: "p", text: "If a code you made yourself is hard to scan, the cause is usually low contrast, a missing margin, a large logo or a dense code printed too small. The [QR Validator](/qr-validator/) measures each of these from an image, and [QR code colours, contrast and logos](/blog/qr-code-colours-contrast-and-logos/) explains the fixes." },
      { type: "h2", id: "safety", text: "Scanning safely" },
      { type: "p", text: "A QR code can point anywhere, and fake codes stuck over real ones on parking meters, posters and restaurant tables are a known scam. Phones show the link before opening it, so take a second to read it:" },
      { type: "ul", items: [
        "Check the domain name is what you expect and spelled correctly.",
        "Be suspicious of a code that immediately asks for card details or a login, especially for parking or payments.",
        "Look for a sticker placed over an original code.",
        "When in doubt, type the organisation's address yourself instead of following the code.",
      ] },
      { type: "p", text: "ScanHatch's scanners never open anything automatically. They show the decoded content and the website's name first, and warn about some common tricks, such as login details hidden in a link." },
    ],
    faq: [
      { q: "Do I need an app to scan QR codes?", a: "Usually not. The camera apps on iPhone and most Android phones read QR codes directly." },
      { q: "Can I scan a QR code from a photo?", a: "Yes. Open the photo in Google Lens or the iPhone Photos app, or upload it to a QR decoder." },
      { q: "Is it safe to scan any QR code?", a: "Scanning only reads the text. The risk comes from opening a link, so check the address your phone shows before you tap it." },
    ],
    relatedTools: ["qr-scanner", "qr-decoder", "scanner", "qr-validator"],
    relatedArticles: ["what-is-a-qr-code", "qr-code-colours-contrast-and-logos", "what-can-a-qr-code-contain"],
    cta: { label: "Scan a QR code now", href: "/qr-scanner/", text: "Use your camera, or upload an image, and see exactly what the code contains before opening it." },
  },
];
