import type { Article } from "../types";

const D = "2026-09-28";

export const QR_GUIDES: Article[] = [
  {
    slug: "how-to-create-a-qr-code",
    title: "How to Create a QR Code (That Actually Scans)",
    metaTitle: "How to Create a QR Code That Scans Reliably",
    description: "A step-by-step guide to making a QR code that scans: choosing the content, keeping it readable, picking the file format and size, and testing before print.",
    category: "how-to", publishedAt: D, updatedAt: D,
    intro: [
      "Making a QR code takes a minute. Making one that still works when it's printed on a poster, stuck to a window or photographed in poor light takes a few more decisions. This guide walks through them using the most common case, a QR code for a website, with notes for other content types.",
    ],
    body: [
      { type: "h2", id: "decide", text: "1. Decide what the code should do" },
      { type: "p", text: "Start with the action you want: open a web page, join WiFi, save a contact, send an email. Each needs a different content type, because phones react to the format of the text inside the code (see [what a QR code can contain](/blog/what-can-a-qr-code-contain/)). If you're not sure, a link to a web page is the most flexible option, because you can update the page later without reprinting the code." },
      { type: "h2", id: "content", text: "2. Prepare the content" },
      { type: "h3", text: "For a website link" },
      { type: "ul", items: [
        "Use the https:// version of the address. Browsers warn about unencrypted pages, and cautious people won't open them from a public code.",
        "Keep it short. `https://example.com/menu` makes a 25 × 25 code; a 113-character link full of tracking parameters needs 41 × 41, with smaller modules at the same printed size.",
        "Prefer a path on your own domain over a third-party short link. If a shortening service disappears, every printed code breaks; your own domain can be redirected whenever you like.",
        "If you want to measure scans, add campaign parameters such as `?utm_source=poster`, and your website analytics will count the visits. Static QR codes don't count scans themselves.",
      ] },
      { type: "p", text: "The [URL QR code generator](/url-qr-code-generator/) is set up for this, and adds https:// if you leave it out." },
      { type: "h3", text: "For other content" },
      { type: "p", text: "Enter details exactly as the receiving device expects them: a WiFi network name with the right capital letters, phone numbers with the country code (+44…), email addresses without typos. The [QR Code Generator](/qr-code-generator/) validates each field and formats the text for you." },
      { type: "h2", id: "design", text: "3. Style it without breaking it" },
      { type: "p", text: "Colours, rounded dots and logos are fine within limits. The rules that matter most:" },
      { type: "ul", items: [
        "Dark code on a light background, with strong contrast.",
        "A clear margin, the quiet zone, of 4 modules around the code.",
        "A logo no larger than about a fifth of the code's width, with error correction set to H.",
        "Leave the three corner squares recognisable.",
      ] },
      { type: "p", text: "The generator warns you as you design if contrast, margin or logo size is risky. The reasons are covered in [QR code colours, contrast and logos](/blog/qr-code-colours-contrast-and-logos/)." },
      { type: "h2", id: "format", text: "4. Choose the right file format" },
      { type: "table", caption: "Which file format to download", head: ["Use", "Format", "Why"], rows: [
        ["Print: posters, flyers, packaging, signs", "SVG or PDF", "Vector files stay perfectly sharp at any size"],
        ["Websites, emails, social media, slides", "PNG", "Works everywhere; choose a large pixel size"],
        ["Documents and presentations", "PNG or SVG", "Most office apps accept both"],
        ["Where transparency isn't supported", "JPG", "Only if nothing else is accepted"],
      ] },
      { type: "p", text: "Avoid enlarging a small PNG for print: it blurs the edges of the modules. Download SVG or PDF instead, or a larger PNG." },
      { type: "h2", id: "size", text: "5. Print it big enough" },
      { type: "p", text: "A common rule of thumb is that a QR code should be at least a tenth as wide as the distance it will be scanned from: 2 cm for a business card held in the hand, 10 cm for a poster read from a metre away. Denser codes need more. [QR code size and quiet zone](/blog/qr-code-size-and-quiet-zone/) has a table of sizes." },
      { type: "h2", id: "test", text: "6. Test before you print a batch" },
      { type: "ol", items: [
        "Scan the downloaded file on screen with two different phones, ideally one iPhone and one Android.",
        "Check the result does exactly what you intended: the page loads on mobile, or the WiFi connects.",
        "Upload the image to the [QR Validator](/qr-validator/) to check its contrast, margin and error-correction margin.",
        "Print one copy at the final size, on the final material, and scan it from the distance people will use.",
      ] },
      { type: "h2", id: "many", text: "Making many codes at once" },
      { type: "p", text: "For tables in a restaurant, product labels or event badges, create a spreadsheet with one row per code and use the [Bulk QR Generator](/bulk-qr-generator/) to produce them all in one ZIP file." },
      { type: "h2", id: "mistakes", text: "Common mistakes" },
      { type: "ul", items: [
        "Linking to a page that isn't mobile-friendly: almost everyone scanning is on a phone.",
        "Printing a code on a curved bottle or behind glossy laminate without testing it.",
        "Putting the code where there's no phone signal, such as an underground car park, when it links to a website.",
        "Using a free “dynamic” code from a service that later disables it unless you pay.",
        "Forgetting a short line of text telling people what the code does.",
      ] },
    ],
    faq: [
      { q: "Do QR codes made with ScanHatch expire?", a: "No. They're static codes: the content is stored in the code itself, so they work for as long as whatever they point to exists." },
      { q: "What's the minimum size for a QR code?", a: "About 2 × 2 cm for scanning up close, and larger for longer distances or denser codes." },
      { q: "Can I change a QR code after printing it?", a: "Not the code itself. If it links to a page on your own website, you can change that page or redirect it." },
    ],
    relatedTools: ["qr-generator", "qr-url", "qr-validator", "bulk-qr"],
    relatedArticles: ["qr-code-size-and-quiet-zone", "qr-code-colours-contrast-and-logos", "static-vs-dynamic-qr-codes"],
    cta: { label: "Create your QR code", href: "/qr-code-generator/", text: "Choose a content type, style it, and download SVG, PDF or PNG." },
  },
  {
    slug: "qr-code-error-correction-explained",
    title: "QR Code Error Correction Explained: L, M, Q and H",
    metaTitle: "QR Code Error Correction Levels (L, M, Q, H)",
    description: "What QR error correction levels L, M, Q and H mean, how Reed-Solomon lets damaged codes scan, how the level changes size, and which to choose.",
    category: "technical", publishedAt: D, updatedAt: D,
    intro: [
      "Every QR code carries extra data that lets a scanner repair damage: a scratch, a smudge, a bit of glare or a logo in the middle. How much extra is set by the error-correction level. Choosing it is a trade-off between robustness and size.",
    ],
    body: [
      { type: "h2", id: "levels", text: "The four levels" },
      { type: "table", caption: "QR code error-correction levels", head: ["Level", "Can restore roughly", "Typical use"], rows: [
        ["L (Low)", "7% of the data", "Clean environments, screens, maximum data in a small code"],
        ["M (Medium)", "15%", "The usual default for print"],
        ["Q (Quartile)", "25%", "Industrial labels, outdoor use, rough surfaces"],
        ["H (High)", "30%", "Codes with logos, or that may get damaged"],
      ] },
      { type: "p", text: "The percentages refer to codewords, the 8-bit chunks the data is split into, not to a fraction of the printed area. That distinction matters and is covered below." },
      { type: "h2", id: "how", text: "How error correction works" },
      { type: "p", text: "QR codes use Reed-Solomon codes, the same family used on CDs, DVDs and in deep-space communication. The encoder treats the data as a set of numbers and calculates extra error-correction codewords from them. Given enough of the combined codewords, the decoder can work out which ones are wrong and what they should have been." },
      { type: "p", text: "Larger codes split their data into several blocks, each with its own error-correction codewords, and interleave the blocks across the symbol. A scratch across one area then damages a little of many blocks rather than all of one, so each block can repair its share." },
      { type: "h2", id: "size", text: "The cost: bigger codes" },
      { type: "p", text: "Error-correction codewords take up space, so a higher level means fewer modules are left for data, and the generator may need a larger version to fit the same content." },
      { type: "table", caption: "The same content at different levels (generated with the ScanHatch engine)", head: ["Content", "L", "M", "Q", "H"], rows: [
        ["`https://example.com/menu` (24 characters)", "25 × 25", "25 × 25", "29 × 29", "29 × 29"],
        ["A 113-character link with tracking parameters", "41 × 41", "45 × 45", "53 × 53", "57 × 57"],
      ] },
      { type: "p", text: "For short content the difference is small. For long content, H can make the code much denser. At the same printed size that means smaller modules and a harder scan, which can undo the benefit." },
      { type: "h2", id: "area", text: "Why “30%” doesn't mean you can cover 30% of the code" },
      { type: "ul", items: [
        "The finder patterns, timing patterns and format information aren't protected by the data's error correction. Cover a finder pattern and the code usually won't be found at all.",
        "Reed-Solomon can repair twice as many known-missing codewords as unknown errors. A clean blank area is easier to recover from than random smudges that make modules read wrongly.",
        "A logo usually damages codewords partially, and several codewords at once, because each codeword's 8 modules are spread across a small region.",
        "Real-world scanning also spends error correction on blur, glare and printing defects, and none of that shows in the file.",
      ] },
      { type: "p", text: "So treat the percentages as capacity to spend carefully, not a target to fill. In our own tests, a logo 22% of the code's width at level H left about half of the error-correction capacity unused. That's a healthy margin." },
      { type: "h2", id: "choose", text: "Which level should you use?" },
      { type: "ul", items: [
        "M for most printed codes without a logo. It balances size and robustness.",
        "L for codes shown on screens, or when you need to fit a lot of data in a small space.",
        "Q for labels that get handled, rubbed or exposed to weather.",
        "H whenever there's a logo or artwork over the code. ScanHatch's generator switches to H automatically when you add a logo.",
      ] },
      { type: "h2", id: "measure", text: "Measuring how much is used" },
      { type: "p", text: "You can't tell by eye how much error correction a logo or damage is using. The [QR Validator](/qr-validator/) decodes an image and reports the share of error correction still unused, alongside contrast and quiet-zone checks. If less than about half is left, a smaller logo or a cleaner print is worth considering." },
    ],
    faq: [
      { q: "Does higher error correction make a code harder to scan?", a: "It can, indirectly. It makes the code denser, so at the same printed size the modules are smaller. For short content the difference is minor." },
      { q: "Can I change the error-correction level of a printed code?", a: "No. It's fixed when the code is generated. You'd need to create and print a new code." },
      { q: "Which level do phone cameras need?", a: "Any level works. The level affects how much damage a code can survive, not which phones can read it." },
    ],
    relatedTools: ["qr-generator", "qr-validator", "qr-scanner"],
    relatedArticles: ["qr-code-colours-contrast-and-logos", "what-is-a-qr-code", "qr-code-size-and-quiet-zone"],
    cta: { label: "Check a QR code's error-correction margin", href: "/qr-validator/", text: "Upload a QR code image to see how much error correction a logo or damage is using." },
  },
  {
    slug: "qr-code-size-and-quiet-zone",
    title: "QR Code Size and Quiet Zone: How Big Should a QR Code Be?",
    metaTitle: "QR Code Size & Quiet Zone: How Big Should It Be?",
    description: "How big to print a QR code for a scanning distance, why the quiet zone matters, how data length affects module size, and how to export sharp print files.",
    category: "technical", publishedAt: D, updatedAt: D,
    intro: [
      "Most QR codes that fail in the real world don't fail because of their content. They fail because they're printed too small for the distance, or because a design eats into the blank margin around them. Both are easy to get right with a few numbers.",
    ],
    body: [
      { type: "h2", id: "distance", text: "Size depends on scanning distance" },
      { type: "p", text: "A widely used rule of thumb is a 10:1 ratio: the code's width should be at least a tenth of the distance it's scanned from. It's a starting point, not a guarantee, because camera quality, lighting and the code's density all move the number." },
      { type: "table", caption: "Suggested minimum widths using the 10:1 rule of thumb", head: ["Where it's scanned from", "Distance", "Minimum width"], rows: [
        ["Business card, product label in the hand", "20–30 cm", "2–3 cm"],
        ["Table card, menu, flyer", "30–50 cm", "3–5 cm"],
        ["Poster on a wall", "1–2 m", "10–20 cm"],
        ["Window sign seen from the pavement", "2–3 m", "20–30 cm"],
        ["Billboard or banner", "5 m and more", "50 cm and more"],
      ] },
      { type: "p", text: "About 2 × 2 cm is a sensible minimum even for close scanning. Smaller codes can work but leave little margin for older phones." },
      { type: "h2", id: "density", text: "Density matters as much as size" },
      { type: "p", text: "What a camera actually needs to resolve is each module, the individual square. The more data in a code, the more modules it has, so the smaller each one is at a given printed width." },
      { type: "example", label: "Example", text: "A short link makes a 25 × 25 grid. Printed 2 cm wide, each module is 0.8 mm. A long tracking link needs 57 × 57 modules at error-correction level H, so at the same 2 cm each module shrinks to about 0.35 mm, which is much harder for a phone to resolve. That code needs printing about twice as wide." },
      { type: "p", text: "If you can't make a code bigger, make it simpler: shorten the link, remove unnecessary tracking parameters, or use a lower error-correction level when there's no logo." },
      { type: "h2", id: "quiet-zone", text: "The quiet zone" },
      { type: "p", text: "The quiet zone is the blank margin around a QR code. The QR code standard (ISO/IEC 18004) specifies 4 modules on every side. Scanners use it to tell where the code ends and the surrounding design begins; text, borders or busy backgrounds right up against the code can make the finder patterns hard to pick out." },
      { type: "ul", items: [
        "The margin needs to be as light as the code's background, not just empty. A code placed on a patterned background still needs its own light border.",
        "Many phones cope with 2 modules, but 4 is what the standard asks for and costs little.",
        "Don't trim the margin off a downloaded image to save space. It's part of the code.",
        "Micro QR, a smaller variant, needs only 2 modules.",
      ] },
      { type: "p", text: "The [QR Code Generator](/qr-code-generator/) adds a 4-module quiet zone by default, and the [QR Validator](/qr-validator/) measures the clear margin in an uploaded image, including margins spoiled by nearby content." },
      { type: "h2", id: "printing", text: "Exporting files that print sharply" },
      { type: "ul", items: [
        "Use SVG or PDF for print. They're vector formats, so the module edges stay crisp at any size.",
        "If you must use PNG, work out the pixels you need: at 300 dpi, a 3 cm code needs about 354 pixels, and a 10 cm poster code about 1,181.",
        "Never stretch a code unevenly. Squashed modules confuse scanners.",
        "Leave the code square in design software, and scale it with the aspect ratio locked.",
      ] },
      { type: "h2", id: "screens", text: "QR codes on screens" },
      { type: "p", text: "On a screen, the equivalent of print size is the displayed size. Codes in presentations and on TV need to be large enough for people at the back of the room; codes on phones for tickets should be displayed at full brightness. Screens show fine detail well, so a lower error-correction level is usually fine." },
    ],
    faq: [
      { q: "What is the smallest QR code that will scan?", a: "Around 2 × 2 cm is a practical minimum for close scanning with a phone. Smaller codes can work with short content and good printing, but test them." },
      { q: "Can a QR code be too big?", a: "Rarely. It just needs to fit entirely in the camera's view from where people stand." },
      { q: "Does the quiet zone have to be white?", a: "It must be as light as the code's background and free of other marks. White is simplest." },
    ],
    relatedTools: ["qr-generator", "qr-validator", "bulk-qr"],
    relatedArticles: ["how-to-create-a-qr-code", "qr-code-colours-contrast-and-logos", "qr-code-error-correction-explained"],
    cta: { label: "Set your QR code's size and margin", href: "/qr-code-generator/", text: "The Size tab sets the quiet zone and export size, and warns if the result is risky." },
  },
  {
    slug: "how-to-create-a-wifi-qr-code",
    title: "How to Create a WiFi QR Code (and Fix One That Won't Connect)",
    metaTitle: "How to Make a WiFi QR Code That Connects",
    description: "Make a QR code that lets guests join your WiFi, share it safely with a guest network, and fix the common reasons a WiFi QR code scans but doesn't connect.",
    category: "how-to", publishedAt: D, updatedAt: D,
    intro: [
      "A WiFi QR code saves you from spelling out a password for every guest. Making one is quick. This guide also covers the parts that aren't obvious: sharing the network safely, and what to check when a phone scans the code but won't join.",
    ],
    body: [
      { type: "h2", id: "gather", text: "What you need" },
      { type: "ul", items: [
        "The network name (SSID), exactly as it appears in your phone's WiFi list. It's case-sensitive: “Home_WiFi” and “home_wifi” are different networks.",
        "The password, exactly as set on the router.",
        "The security type, which is WPA/WPA2/WPA3 on almost every modern router.",
        "Whether the network is hidden (not broadcast). Most aren't.",
      ] },
      { type: "p", text: "Your router's admin page or the sticker on the router shows the name and password. If you've changed them, use the current values." },
      { type: "h2", id: "create", text: "Creating the code" },
      { type: "ol", items: [
        "Open the [WiFi QR code generator](/wifi-qr-code-generator/).",
        "Enter the network name and password, and choose the security type.",
        "Tick “Hidden network” only if your router doesn't broadcast the name.",
        "Download the code. Use PDF or SVG if you're going to print it.",
        "Test it with a phone that isn't already connected, or “forget” the network on your phone first.",
      ] },
      { type: "example", label: "What's inside the code (fictional example)", text: "`WIFI:T:WPA;S:Example Guest;P:correct-horse-42;;`: T is the security type, S the network name and P the password. A hidden network adds `H:true;`." },
      { type: "p", text: "Special characters are escaped automatically. In this format a semicolon, colon, comma, quote mark or backslash inside a name or password must be preceded by a backslash, or phones cut the value short. Getting that wrong by hand is a common reason homemade codes fail." },
      { type: "h2", id: "safety", text: "Share a guest network, not your main one" },
      { type: "p", text: "The password inside a WiFi QR code is plain text. Anyone who scans it can read it, and anyone who photographs the code can scan it later. For anything displayed in public, such as a café counter, a holiday let or a meeting room:" },
      { type: "ul", items: [
        "Use your router's guest network if it has one. Guests get internet access, but not your computers, printers or smart-home devices.",
        "Choose a guest password you don't use anywhere else.",
        "Change the guest password occasionally, and print a new code when you do. The old code simply stops working.",
      ] },
      { type: "h2", id: "troubleshooting", text: "When the code scans but won't connect" },
      { type: "table", caption: "Why a WiFi QR code fails to connect", head: ["Symptom", "Likely cause", "Fix"], rows: [
        ["“Unable to join” or wrong password", "Password changed since the code was made, or mistyped", "Check the password on the router and make a new code"],
        ["Network not found", "Name doesn't match exactly (capitals, spaces), or the phone is out of range", "Copy the name from your phone's WiFi list"],
        ["Hidden network never connects", "Hidden flag not set", "Tick “Hidden network” and regenerate"],
        ["Some newer phones fail, older ones work", "Router is in WPA3-only mode", "Try the router's WPA2/WPA3 mixed mode"],
        ["Connects but no internet", "The network has a sign-in page (captive portal), or the router blocks new devices", "Open a browser to sign in; check MAC filtering on the router"],
        ["Only shows text, no “Join” button", "Older phone or camera app without WiFi-code support", "Use Google Lens, the Android WiFi settings scanner, or type the details"],
        ["Work network with a username", "WPA2/WPA3-Enterprise (802.1X) networks", "Standard WiFi QR codes can't carry enterprise logins"],
      ] },
      { type: "p", text: "The [QR Validator](/qr-validator/) decodes a WiFi code and checks it: a missing network name, a password too short for WPA, or a password given for an open network are all flagged." },
      { type: "h2", id: "printing", text: "Printing a WiFi sign" },
      { type: "ul", items: [
        "Print the code at least 3 cm wide for scanning from arm's length.",
        "Add a line of text, such as “Scan to join the guest WiFi”, and the network name, so people can connect manually if their phone doesn't support it.",
        "Laminated signs reflect light. Test the finished sign, not just the file.",
      ] },
    ],
    faq: [
      { q: "Can people see my WiFi password from the QR code?", a: "Yes. The password is stored as readable text, so anyone who scans the code can see it. Use a guest network for public codes." },
      { q: "Does a WiFi QR code stop working?", a: "Only if you change the network name, password or security type. Then you need a new code." },
      { q: "Can one QR code hold two networks?", a: "No. Each code holds one network. Print one code per network, for example 2.4 GHz and 5 GHz if they have different names." },
    ],
    relatedTools: ["qr-wifi", "qr-validator", "qr-scanner", "qr-generator"],
    relatedArticles: ["what-can-a-qr-code-contain", "how-to-scan-a-qr-code", "qr-code-size-and-quiet-zone"],
    cta: { label: "Create a WiFi QR code", href: "/wifi-qr-code-generator/", text: "Enter your network details; special characters are escaped for you." },
  },
  {
    slug: "static-vs-dynamic-qr-codes",
    title: "Static vs Dynamic QR Codes: What's the Difference?",
    metaTitle: "Static vs Dynamic QR Codes: What's the Difference?",
    description: "How static and dynamic QR codes differ, what dynamic QR services do, the risks of relying on them, and how to get editable links with your own website.",
    category: "technical", publishedAt: D, updatedAt: D,
    intro: [
      "Many QR code services advertise “dynamic” codes that you can edit after printing and that count scans, often after a free trial. The difference from a static code is simple once you see what's inside each one, and that also shows the trade-offs.",
    ],
    body: [
      { type: "h2", id: "static", text: "Static QR codes" },
      { type: "p", text: "A static QR code contains the final content directly: the web address, WiFi details or contact card. Scanning it takes the phone straight there. No other service is involved." },
      { type: "ul", items: [
        "It works for as long as the content does: indefinitely for WiFi or contact codes, and as long as the web page exists for links.",
        "It can't be changed after printing, because the content is the pattern.",
        "It doesn't count scans, because no one sees the scan except the phone and the destination website.",
      ] },
      { type: "p", text: "ScanHatch makes static QR codes only. They don't expire, and they don't depend on ScanHatch staying in business." },
      { type: "h2", id: "dynamic", text: "Dynamic QR codes" },
      { type: "p", text: "A “dynamic” QR code is a static QR code containing a short link to the service provider's own server, such as `https://qr-provider.example/Ab3xY`. When scanned, the provider records the scan and redirects the phone to whatever destination you've set in your account." },
      { type: "p", text: "Changing the destination later changes the redirect, not the printed code, which is why it appears editable. The scan counts are the provider's redirect logs." },
      { type: "h2", id: "compare", text: "Side by side" },
      { type: "table", caption: "Static and dynamic QR codes compared", head: ["", "Static", "Dynamic (via a provider)"], rows: [
        ["What's inside", "The final content", "A short link to the provider"],
        ["Edit after printing", "No", "Yes, through the provider's account"],
        ["Scan statistics", "Not by itself (use your website analytics)", "Yes, from the provider"],
        ["Works if the provider closes or you stop paying", "Yes", "No. The redirect stops working"],
        ["Extra step when scanned", "None", "A redirect through a third-party server"],
        ["Privacy", "Only the destination sees the visit", "The provider also records each scan"],
        ["WiFi, contacts, phone numbers", "Work offline", "Usually converted to a web page first"],
      ] },
      { type: "h2", id: "risk", text: "The main risk of dynamic codes" },
      { type: "p", text: "Printed codes last years, and a dynamic code works only as long as the provider keeps redirecting it. Some services disable codes when a free trial ends or a subscription lapses, which leaves menus, packaging and signage pointing at an error page or an advert. Before relying on dynamic codes for anything printed in quantity, check the terms for what happens to existing codes if you cancel." },
      { type: "h2", id: "own-domain", text: "The middle way: a static code with your own link" },
      { type: "p", text: "You can get most of the benefits of dynamic codes without depending on a provider:" },
      { type: "ol", items: [
        "Pick an address on your own domain, such as `https://example.com/menu`.",
        "Make a static QR code for it with the [URL QR code generator](/url-qr-code-generator/).",
        "When the destination changes, update that page or set up a redirect on your website. The printed code keeps working.",
        "To count scans, add campaign parameters such as `?utm_source=table-card` to the link. Your website analytics will then report visits from the code.",
      ] },
      { type: "p", text: "The one thing this doesn't give you is editing non-web content: a WiFi or contact code always needs reprinting if the details change." },
      { type: "h2", id: "choose", text: "Which should you use?" },
      { type: "ul", items: [
        "WiFi, contact cards, phone numbers and anything permanent: static.",
        "Links on print that will stay in circulation: static, pointing to a page on your own domain.",
        "Short campaigns where you want the provider's dashboard and accept the dependency: dynamic may be convenient, but read the cancellation terms.",
      ] },
    ],
    faq: [
      { q: "Do static QR codes expire?", a: "No. The content is in the code itself. A link code stops being useful only if the web page it points to is removed." },
      { q: "Can I track scans of a static QR code?", a: "Not directly, but adding campaign parameters to a link lets your website analytics count visits from the code." },
      { q: "Does ScanHatch offer dynamic QR codes?", a: "No. ScanHatch creates static codes only, so your codes don't depend on a ScanHatch account or server." },
    ],
    relatedTools: ["qr-url", "qr-generator", "qr-validator", "bulk-qr"],
    relatedArticles: ["how-to-create-a-qr-code", "what-is-a-qr-code", "what-can-a-qr-code-contain"],
    cta: { label: "Create a static QR code for your link", href: "/url-qr-code-generator/", text: "Free, no account, and no expiry." },
  },
  {
    slug: "qr-code-colours-contrast-and-logos",
    title: "QR Code Colours, Contrast and Logos: Designing Codes That Scan",
    metaTitle: "QR Code Colours, Contrast and Logos: Design Rules",
    description: "How to use brand colours, gradients, rounded styles and logos on a QR code without breaking it: contrast, inverted colours, logo size, error correction and testing.",
    category: "technical", publishedAt: D, updatedAt: D,
    intro: [
      "A branded QR code looks better on packaging and posters than plain black and white, and phones cope with far more styling than people expect. They do have limits, though, and most unreadable “designer” codes break the same few rules.",
    ],
    body: [
      { type: "h2", id: "contrast", text: "Contrast comes first" },
      { type: "p", text: "Scanners convert the image to light and dark and look for the pattern. What matters is the difference in brightness between the modules and the background, not the colours themselves. A dark navy on cream is fine; a mid-grey on a light grey often isn't, even though it looks clear on a bright screen." },
      { type: "ul", items: [
        "Use a dark foreground on a light background. Aim for a contrast ratio of at least 4:1; the higher the better.",
        "Check brightness, not hue: red and green of similar brightness can look distinct to you but nearly identical to a camera.",
        "Test printed colours, not just the screen. Inks, especially on uncoated paper, often print lighter and duller than they look in a design app.",
      ] },
      { type: "p", text: "The [QR Code Generator](/qr-code-generator/) warns when contrast is low as you pick colours, and the [QR Validator](/qr-validator/) measures the contrast in an uploaded image." },
      { type: "h2", id: "inverted", text: "Light codes on dark backgrounds" },
      { type: "p", text: "An inverted code, with light modules on a dark background, is allowed by the QR code standard, but many scanners still don't read it, and others read it slowly. If a dark design needs a code, put a normal dark-on-light code inside a light panel instead." },
      { type: "h2", id: "gradients", text: "Gradients and transparent backgrounds" },
      { type: "ul", items: [
        "Gradients work if every part of the gradient is dark enough against the background. Check the lightest end, not the average.",
        "A transparent background makes the code take on whatever it's placed on. That's fine on plain light paper, but risky on photos, patterns or dark packaging.",
        "Keep the quiet zone (4 modules) clear and light, even when the code sits on a coloured design.",
      ] },
      { type: "h2", id: "shapes", text: "Rounded dots and custom corners" },
      { type: "p", text: "Rounded or dotted modules scan well because scanners sample the centre of each module. Custom corner shapes are also fine as long as the three finder patterns still look like a square within a square with a gap between them. Those are what scanners search for first." },
      { type: "h2", id: "logos", text: "Adding a logo" },
      { type: "p", text: "A logo in the middle of a QR code covers modules that carry data. The code still scans because error correction rebuilds the missing data, and that's all the logo is doing: using up robustness that would otherwise protect against glare, dirt and blur." },
      { type: "ul", items: [
        "Set error correction to H (the generator does this automatically when you add a logo).",
        "Keep the logo to roughly a fifth of the code's width. In our tests, a logo 22% wide left about half the error correction unused, which is a comfortable margin.",
        "Clear the modules behind the logo and give it a small light border rather than overlaying it on the pattern.",
        "Never place a logo over a finder pattern in the corners.",
      ] },
      { type: "p", text: "[QR code error correction explained](/blog/qr-code-error-correction-explained/) covers why the “30%” figure for level H doesn't mean a logo can cover 30% of the code." },
      { type: "h2", id: "checklist", text: "Design checklist" },
      { type: "table", caption: "Quick design checks", head: ["Check", "Safe choice"], rows: [
        ["Foreground and background", "Dark on light, contrast 4:1 or more"],
        ["Inverted (light on dark)", "Avoid for public codes"],
        ["Quiet zone", "4 modules, light and empty"],
        ["Logo size", "About 20% of the width, error correction H"],
        ["Finder patterns", "Unobstructed and recognisable"],
        ["Testing", "Several phones, printed at final size and material"],
      ] },
      { type: "p", text: "After designing, upload the final image to the [QR Validator](/qr-validator/). It reports contrast, quiet zone, module size and how much error correction the design is using. Then scan a printed proof, because the file can't show glare or ink spread." },
    ],
    faq: [
      { q: "Can a QR code be any colour?", a: "Yes, as long as the modules are much darker than the background. Brightness contrast matters more than the colour itself." },
      { q: "How big can a logo be?", a: "With error correction H, keeping it to about a fifth of the code's width leaves a sensible safety margin. Larger logos may still scan but are less reliable." },
      { q: "Why won't my white QR code on a black background scan?", a: "Many scanners don't support inverted codes. Use dark modules on a light background." },
    ],
    relatedTools: ["qr-generator", "qr-validator", "qr-scanner"],
    relatedArticles: ["qr-code-error-correction-explained", "qr-code-size-and-quiet-zone", "how-to-create-a-qr-code"],
    cta: { label: "Design a QR code", href: "/qr-code-generator/", text: "Colours, gradients, dot styles and logos, with live readability warnings." },
  },
];
